#!/usr/bin/env python
"""Build a sanitized source-visible noncommercial public package.

The public package is intentionally not a raw copy of the private research
workspace. It contains a small offline demo, licensing material, and disclosure
boundaries while excluding private prompts, formal reproduction harnesses,
live-run artifacts, internal reports, and AGENTS.md.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import shutil
import sys
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PUBLIC_NAME = "CivicMarketEngine"
PUBLIC_PACKAGE = "civic-market-engine-public"
DEFAULT_NAME = f"civic_market_engine_public_snapshot_{dt.datetime.now().strftime('%Y%m%d')}"


ROOT_COPY_FILES = [
    ".gitignore",
    "ATTRIBUTION.md",
    "LICENSE",
    "NOTICE",
]

SAFE_SOURCE_FILES = [
    "database.py",
    "models.py",
    "mortgage_system.py",
    "property_initializer.py",
]

SCRIPT_FILES = [
    "scripts/build_public_snapshot.py",
    "scripts/check_public_snapshot.py",
    "scripts/public_smoke_test.py",
]

TEST_FILES = [
    "tests/test_public_package.py",
]

TREE_RULES = [
    (".container", {".example", ".md", ".ps1", ".yaml", ".yml", ""}),
    ("licenses", {".txt"}),
]

PRIVATE_BOUNDARIES = [
    "AGENTS.md",
    "prompts/",
    "agent_behavior.py",
    "transaction_engine.py",
    "simulation_runner.py",
    "formal_reproduction/",
    "reports/",
    "results/",
    "live LLM run outputs",
    "stage gate reports",
    "formal reproduction matrices",
    "internal prompt and boundary documents",
]

EXCLUDED_PARTS = {
    ".codex",
    ".git",
    ".pytest_cache",
    ".venv",
    "__pycache__",
    "archive",
    "build",
    "dist",
    "env",
    "formal_reproduction",
    "logs",
    "node_modules",
    "output",
    "prompts",
    "reports",
    "results",
    "venv",
}

EXCLUDED_NAMES = {
    ".env",
    ".env.deepseek",
    ".env.deepseek.example",
    ".llm_exact_cache.sqlite3",
    "AGENTS.md",
    "NIGHT_RUN.md",
    "agent_behavior.py",
    "order_lifecycle.log",
    "simulation_run.log",
    "simulation_runner.py",
    "test_reporting.db",
    "transaction_engine.py",
}

EXCLUDED_PREFIXES = (
    "autopilot_release_loop",
    "continue_formal_medium_matrix",
    "night_run_",
    "rebuild_proof_matrix_",
    "run_formal_medium_matrix",
    "run_night",
)


README_TEXT = """# CivicMarketEngine

Source-visible, noncommercial real-estate market simulation demo.

This public package is a sanitized demo package. It is not the private research
workspace and it does not contain the private LLM prompts, internal stage
reports, formal reproduction harnesses, live LLM artifacts, or AGENTS.md
boundary contract.

## What is included

- A small offline smoke demo: `python scripts/public_smoke_test.py --rounds 1 --seed 42`
- Public licensing and attribution material.
- A snapshot checker that blocks runtime artifacts, secrets, local paths, and
  private prompt / formal reproduction files.
- A small set of safe model and finance helper source files for inspection.

## What is intentionally excluded

- Private prompt assets and prompt tuning strategy.
- `AGENTS.md` and internal LLM/code boundary instructions.
- Formal reproduction harnesses, staged gate reports, and long-run matrices.
- Live LLM outputs, `.env` files, databases, spreadsheets, logs, caches, and
  local result folders.
- The private full simulation runtime.

## Quick check

```bash
python scripts/check_public_snapshot.py .
python scripts/public_smoke_test.py --rounds 1 --seed 42
```

The public smoke is offline and deterministic. It demonstrates artifact shape
only; it is not a formal reproduction result and it is not investment advice.

## License

This public package is distributed under the PolyForm Noncommercial License
1.0.0. Commercial use requires separate permission.
"""


BOUNDARY_TEXT = """# Public Release Boundary

`CivicMarketEngine` is the noncommercial, source-visible public package.

It is generated by whitelist copying and explicit replacement. It must not be
created by copying the private workspace wholesale.

## Public Package Allows

- Offline mock smoke tests.
- Public documentation, licensing, attribution, and minimal examples.
- Non-sensitive helper code that does not expose private prompts or internal
  formal reproduction machinery.

## Public Package Excludes

- Private prompts and prompt tuning strategy.
- `AGENTS.md` and internal LLM/code boundary text.
- Formal reproduction harnesses and staged gate reports.
- Live LLM outputs and result artifacts.
- Secrets, local paths, caches, databases, spreadsheets, logs, and generated
  result folders.

## Positioning

This package is for noncommercial review, education, and mechanism discussion.
It is not a price prediction tool, not a production trading system, and not an
investment recommendation.
"""


REQUIREMENTS_TEXT = """openpyxl>=3.1
pytest>=7.4.0
"""


EXAMPLE_README_TEXT = """# Minimal Public Smoke

This example runs the offline public demo only. It does not call live LLMs and
does not import the private full simulation runtime.

From the public package root:

```powershell
powershell -ExecutionPolicy Bypass -File ./examples/cli_minimal_repro/run_mock_smoke.ps1
```

Equivalent direct command:

```powershell
python ./scripts/public_smoke_test.py --rounds 1 --seed 42
```

The smoke creates temporary `simulation.db` and `01_result_bundle.xlsx` files
and deletes them automatically unless `--keep-output` is passed to the Python
script. This is an artifact-shape check, not formal reproduction evidence.
"""


EXAMPLE_PS1_TEXT = """Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

python ./scripts/public_smoke_test.py --rounds 1 --seed 42
"""


CONTAINER_README_TEXT = """# CivicMarketEngine Development Container

This folder contains an optional local development container for the public
noncommercial demo package. It is intended for repeatable local checks and
does not include private credentials, private prompt material, or generated
run results.

## Prerequisites

- Docker: https://docs.docker.com/engine/install/
- Docker Compose: https://docs.docker.com/compose/install/

## Configure Environment

Create a local `.env` file from the public template only when needed. Do not
commit `.env`.

```bash
cd .container
cp .env.example .env
```

The offline public smoke test does not require external service credentials.

## Start Container

```bash
docker compose up -d
```

## Enter the Container

```bash
docker compose exec atlas-market-engine bash
```

Typical public checks:

```bash
python scripts/check_public_snapshot.py .
python scripts/public_smoke_test.py --rounds 1 --seed 42
python -m pytest tests/test_public_package.py -q
```

## Stop and Remove

```bash
docker compose down
```

## Public Package Boundary

The container setup is a development aid only. Public snapshots must still
exclude local `.env` files, result folders, logs, databases, spreadsheets,
caches, and any private research workspace material.
"""


def _as_rel(path: str) -> Path:
    return Path(path.replace("/", "\\"))


def _assert_safe_output(output_dir: Path) -> Path:
    output_dir = output_dir.resolve()
    source_root = ROOT.resolve()
    if output_dir == source_root or source_root in output_dir.parents:
        raise RuntimeError(f"Refuse to build a snapshot inside the source tree: {output_dir}")
    if output_dir.anchor == str(output_dir):
        raise RuntimeError(f"Refuse to use a drive root as output: {output_dir}")
    return output_dir


def _reset_output_dir(output_dir: Path, *, force: bool) -> None:
    if output_dir.exists():
        if not force:
            raise RuntimeError(f"Output directory already exists. Pass --force to replace it: {output_dir}")
        if not output_dir.is_dir():
            raise RuntimeError(f"Output path exists but is not a directory: {output_dir}")
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)


def _should_skip(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    if set(rel.parts) & EXCLUDED_PARTS:
        return True
    if path.name in EXCLUDED_NAMES:
        return True
    if path.suffix.lower() in {".db", ".db-journal", ".sqlite", ".xlsx", ".pyc", ".log", ".tmp"}:
        return True
    return any(path.name.startswith(prefix) for prefix in EXCLUDED_PREFIXES)


def _copy_file(rel_path: Path, output_dir: Path, copied: list[str], *, required: bool = True) -> None:
    src = ROOT / rel_path
    if not src.exists():
        if required:
            raise FileNotFoundError(f"Required public package file is missing: {rel_path.as_posix()}")
        return
    if _should_skip(src):
        return
    dst = output_dir / rel_path
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    rel_posix = rel_path.as_posix()
    if rel_posix not in copied:
        copied.append(rel_posix)


def _copy_tree(rel_dir: Path, suffixes: set[str], output_dir: Path, copied: list[str]) -> None:
    src_dir = ROOT / rel_dir
    if not src_dir.exists():
        return
    for src in sorted(src_dir.rglob("*")):
        if not src.is_file() or _should_skip(src):
            continue
        suffix = src.suffix.lower()
        if suffix not in suffixes and "" not in suffixes:
            continue
        rel_path = src.relative_to(ROOT)
        _copy_file(rel_path, output_dir, copied)


def _write_text_file(output_dir: Path, rel_path: str, text: str, copied: list[str]) -> None:
    rel = _as_rel(rel_path)
    dst = output_dir / rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(text.rstrip() + "\n", encoding="utf-8")
    rel_posix = rel.as_posix()
    if rel_posix not in copied:
        copied.append(rel_posix)


def _write_json_file(output_dir: Path, rel_path: str, payload: dict, copied: list[str]) -> None:
    rel = _as_rel(rel_path)
    dst = output_dir / rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    rel_posix = rel.as_posix()
    if rel_posix not in copied:
        copied.append(rel_posix)


def _write_generated_public_files(output_dir: Path, copied: list[str]) -> None:
    _write_text_file(output_dir, "README.md", README_TEXT, copied)
    _write_text_file(output_dir, ".container/README.md", CONTAINER_README_TEXT, copied)
    _write_text_file(output_dir, "docs/PUBLIC_RELEASE_BOUNDARY.md", BOUNDARY_TEXT, copied)
    _write_text_file(output_dir, "examples/cli_minimal_repro/README.md", EXAMPLE_README_TEXT, copied)
    _write_text_file(output_dir, "examples/cli_minimal_repro/run_mock_smoke.ps1", EXAMPLE_PS1_TEXT, copied)
    _write_text_file(output_dir, "requirements.txt", REQUIREMENTS_TEXT, copied)
    _write_json_file(
        output_dir,
        "package.json",
        {
            "name": PUBLIC_PACKAGE,
            "version": "1.0.0",
            "description": "Source-visible noncommercial public demo for CivicMarketEngine.",
            "scripts": {
                "test:public": "python -m pytest tests/test_public_package.py -q",
                "smoke:public": "python scripts/public_smoke_test.py --rounds 1 --seed 42",
                "check:public": "python scripts/check_public_snapshot.py .",
            },
            "license": "SEE LICENSE IN LICENSE",
        },
        copied,
    )
    _write_json_file(
        output_dir,
        "package-lock.json",
        {
            "name": PUBLIC_PACKAGE,
            "version": "1.0.0",
            "lockfileVersion": 3,
            "requires": True,
            "packages": {
                "": {
                    "name": PUBLIC_PACKAGE,
                    "version": "1.0.0",
                    "license": "SEE LICENSE IN LICENSE",
                }
            },
        },
        copied,
    )


def _write_manifest(output_dir: Path, copied: list[str]) -> Path:
    manifest = {
        "name": DEFAULT_NAME,
        "public_name": PUBLIC_NAME,
        "generated_at": dt.datetime.now().isoformat(timespec="seconds"),
        "profile": "source-visible-noncommercial-sanitized",
        "license": "PolyForm Noncommercial License 1.0.0",
        "copied_file_count": len(copied),
        "copied_files": sorted(set(copied)),
        "private_boundaries_excluded": PRIVATE_BOUNDARIES,
        "excluded_boundaries": sorted(EXCLUDED_PARTS | EXCLUDED_NAMES),
        "notes": [
            "This package is generated by whitelist copying plus generated public files.",
            "It intentionally excludes private prompts, AGENTS.md, formal reproduction harnesses, internal reports, live LLM outputs, local run results, logs, caches, databases, spreadsheets, and secrets.",
        ],
    }
    manifest_path = output_dir / "SNAPSHOT_MANIFEST.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return manifest_path


def _scan_snapshot(output_dir: Path) -> list[dict[str, str]]:
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from scripts.check_public_snapshot import scan_snapshot

    return scan_snapshot(output_dir)


def _make_zip(output_dir: Path, *, force: bool) -> Path:
    zip_path = output_dir.with_suffix(".zip")
    if zip_path.exists():
        if not force:
            raise RuntimeError(f"Zip already exists. Pass --force to replace it: {zip_path}")
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(output_dir.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(output_dir).as_posix())
    return zip_path


def build_snapshot(output_dir: Path, *, force: bool = False, make_zip: bool = False) -> dict[str, object]:
    output_dir = _assert_safe_output(output_dir)
    _reset_output_dir(output_dir, force=force)

    copied: list[str] = []
    for item in ROOT_COPY_FILES + SAFE_SOURCE_FILES + SCRIPT_FILES + TEST_FILES:
        _copy_file(_as_rel(item), output_dir, copied)
    for rel_dir, suffixes in TREE_RULES:
        _copy_tree(_as_rel(rel_dir), suffixes, output_dir, copied)
    _write_generated_public_files(output_dir, copied)

    manifest_path = _write_manifest(output_dir, copied)
    findings = _scan_snapshot(output_dir)
    if findings:
        raise RuntimeError("Snapshot checker failed:\n" + json.dumps(findings, ensure_ascii=False, indent=2))

    zip_path = _make_zip(output_dir, force=force) if make_zip else None
    return {
        "ok": True,
        "public_name": PUBLIC_NAME,
        "snapshot_dir": str(output_dir),
        "manifest": str(manifest_path),
        "copied_file_count": len(set(copied)),
        "zip": str(zip_path) if zip_path else "",
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=f"Build a clean {PUBLIC_NAME} public snapshot.")
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT.parent / DEFAULT_NAME,
        help="Output directory. Defaults to a sibling of the current repository.",
    )
    parser.add_argument("--force", action="store_true", help="Replace the output directory if it already exists.")
    parser.add_argument("--zip", action="store_true", help="Also create a .zip next to the output directory.")
    args = parser.parse_args(argv)

    try:
        result = build_snapshot(args.output, force=bool(args.force), make_zip=bool(args.zip))
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
